# -*- coding: utf-8 -*-
"""Tugas _Analisis_Path_Testing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13gyAzrPti3sBhUfK1zVzCLkczWgnApjB
"""

def hitung_nilai_mahasiswa():
    print("=== Sistem Penilaian Akhir UIN JKT ===")
    try:
        # Node 1: Input dan perhitungan nilai akhir
        formatif = float(input("Masukkan nilai Tugas/Formatif (0-100): "))
        uts = float(input("Masukkan nilai UTS (0-100): "))
        uas = float(input("Masukkan nilai UAS (0-100): "))

        nilai_akhir = (0.20 * formatif) + (0.30 * uts) + (0.50 * uas)

        # Evaluasi percabangan (Nodes 2 - 14)
        if nilai_akhir >= 80:
            huruf = 'A'
        elif nilai_akhir >= 75:
            huruf = 'A-'
        elif nilai_akhir >= 70:
            huruf = 'B'
        elif nilai_akhir >= 65:
            huruf = 'B-'
        elif nilai_akhir >= 60:
            huruf = 'C'
        elif nilai_akhir >= 50:
            huruf = 'D'
        else:
            huruf = 'E'

        # Node 15: Return/Selesai
        print(f"\nNilai Akhir Angka : {nilai_akhir:.2f}")
        print(f"Nilai Akhir Huruf : {huruf}")

    except ValueError:
        print("Error: Harap masukkan input berupa angka!")

if __name__ == "__main__":
    hitung_nilai_mahasiswa()